# Generated by Django 4.2.2 on 2023-07-17 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ormexamples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_many',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
                ('cutomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle_many', to='ormexamples.customer_one')),
            ],
        ),
    ]
