# Generated by Django 4.2.2 on 2023-07-18 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormexamples', '0002_customer_one_vehicle_many'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
        migrations.AlterModelTable(
            name='customer_one',
            table='Customer_one',
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='Vehicle',
        ),
        migrations.AlterModelTable(
            name='vehicle_many',
            table='Vehicle_many',
        ),
    ]
