# Generated by Django 4.2.2 on 2023-07-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormexamples', '0003_alter_customer_table_alter_customer_one_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='customer_one',
            table='customer_one',
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='vehicle',
        ),
        migrations.AlterModelTable(
            name='vehicle_many',
            table='vehicle_many',
        ),
    ]
